name: Maven CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Checkout
    - name: Checkout
      uses: actions/checkout@v4

    # Env Setup
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build & Test
    - name: Build & Test
      run: mvn -B clean install --file pom.xml

    # List the current dir
    - name: List the current directory
      run: ls -a
