name: test-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Checkout
    - name: Checkout
      uses: actions/checkout@v4

    # Env Setup
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build & Test
    - name: Build & Test
      run: mvn -B clean compile source:jar resources:testResources package install

    # List the target folder
    - name: List the target folder
      run: |
        cd target
        ls -a
    # Publish JAR Files
    - name: Publish JAR
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: |
          **/target/*.jar
